#!/bin/bash
# DEPENDENCIES: go get github.com/andres-erbsen/dename/{dnmgr/dnmgr,dnmlookup}
# USAGE: dnget <distributor> <filename>
# WORKING EXAMPLE: dnget andres tor-browser-linux64-3.6.2_en-US.tar.xz
# To publish something: dnmgr set <name> 134625 "<sha256sum-as-hex> <download-url>"

distributor="$1"
filename="$2"
DNGET_FIELD=134625
record="$(dnmlookup "$distributor" "$DNGET_FIELD" | grep -- "/$filename\$" | head -1 | sed 's/\s\+/\t/g')"
echo "$record"
hash="$(echo "$record" | cut -f1)"
url="$(echo "$record" | cut -f2)"
curl --progress-bar --proto =http,https,ftp,ftps --url "$url" --output "$filename"
echo "$hash  $filename" | sha256sum --check || echo 'Verification failed. It is probably not a good idea to use this file.'
